# pass the following cli using a yml (equalivant to kedro run --env base --pipeline fetch_preprocess --params ...)
run:
  env: base                   # conf/base
  pipeline: fetch_preprocess  # run which pipeline in pipeline_registry
  params:                     # additional params apart from parameters.yml
    dataset:
      dir: data/01_raw
      df_sales: sales_train_evaluation.csv
      df_calendar: calendar.csv
      df_prices: sell_prices.csv

    trimming:
      test_size: 28
      start_date: "2016"

    features:
      ma_win: [7, 28]
      ma_key: [
        ['id'],     # id lv
        []          # global lv
      ]
      lag_range: [1, 1]
      avg: [
        ['id'],
      ]
